# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Android.gitlab-ci.yml

# Read more about this script on this blog post https://about.gitlab.com/2018/10/24/setting-up-gitlab-ci-for-android-projects/, by Jason Lenny
# If you are interested in using Android with FastLane for publishing take a look at the Android-Fastlane template.
stages:
  - build
  - quality
  - test

.android_template_standard:
  image: registry-scl-staging.svc.meshcore.net/kazan-mobile/awl-android-sdk:java17
  tags:
    - docker-M
    - kazan-M

# Make Project
assemble:
  extends: .android_template_standard
  interruptible: true
  stage: build
  script:
    - ./gradlew :app:assembleDebug
  artifacts:
    paths:
      - app/build/outputs/
  tags:
    - docker-M
    - kazan-M

# Basic android and gradle stuff
# Check linting
lint:
  extends: .android_template_standard
  interruptible: true
  stage: quality
  script:
    - ./gradlew :app:lintProdDebug
  artifacts:
    paths:
      - app/build/lint/reports/lint-results-debug.html
    expose_as: "lint-report"
    when: always
    expire_in: 1 day
  tags:
    - docker-M
    - kazan-M

# Run all tests, if any fails, interrupt the pipeline(fail it)
Tests:
  extends: .android_template_standard
  needs: [ lint, assemble, Detekt ]
  interruptible: true
  stage: test
  script:
    - ./gradlew :app:testProdDebug
  tags:
    - docker-M
    - kazan-M

Detekt:
  extends: .android_template_standard
  stage: quality
  script:
    - ./gradlew detekt
  artifacts:
    paths:
      - app/build/reports/detekt
    expire_in: 1 day
  tags:
    - docker-M
    - kazan-M
  interruptible: true